apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-17T12:51:44Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "12649"
  uid: b4963826-3862-44a1-8691-08bff7467bb2
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.106.34.156
  clusterIPs:
  - 10.106.34.156
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32545
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
